# Generated by Django 2.1.2 on 2018-11-14 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
    ]
