# Generated by Django 2.1.2 on 2018-11-08 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=20, verbose_name='头像')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('birthday', models.DateTimeField(verbose_name='出生日期')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
