# Generated by Django 2.1.2 on 2018-11-11 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workexp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='edu_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.EducationExp'),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ProjectExp'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.WorkExp'),
        ),
        migrations.AddField(
            model_name='projectexp',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='positionresumestatus',
            name='position',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.PositionInfo'),
        ),
        migrations.AddField(
            model_name='positionresumestatus',
            name='resume',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Resume'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='org',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.OrgInfo'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='resume',
            field=models.ManyToManyField(to='index.Resume'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job_label3',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job_Label2', verbose_name='父标签ID'),
        ),
        migrations.AddField(
            model_name='job_label2',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job_Label1', verbose_name='父标签ID'),
        ),
        migrations.AddField(
            model_name='huntingintent',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationexp',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
