# Generated by Django 2.1.2 on 2018-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='distinct',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='区/县'),
        ),
    ]
