# Generated by Django 2.1.2 on 2018-11-09 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_auto_20181108_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50, verbose_name='学校')),
                ('start_date', models.DateTimeField(verbose_name='起始时间')),
                ('end_date', models.DateTimeField(verbose_name='终止时间')),
                ('education', models.DateTimeField(max_length=50, verbose_name='学历')),
                ('subject', models.CharField(max_length=50, verbose_name='专业')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HuntingIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='求职意向')),
                ('position_type', models.CharField(max_length=20, verbose_name='职位类型')),
                ('city', models.CharField(max_length=50, verbose_name='期望城市')),
                ('satrt_salary', models.CharField(max_length=20, verbose_name='期望起始薪资')),
                ('end_salary', models.CharField(max_length=20, verbose_name='期望最高薪资')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('start_date', models.DateTimeField(verbose_name='起始时间')),
                ('end_date', models.DateTimeField(verbose_name='终止时间')),
                ('url', models.CharField(max_length=100, verbose_name='项目链接')),
                ('description', models.CharField(max_length=500, verbose_name='项目描述')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.EducationExp')),
                ('project_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.ProjectExp')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='公司')),
                ('tag', models.CharField(max_length=20, verbose_name='行业标签')),
                ('department', models.CharField(max_length=50, verbose_name='部门')),
                ('type', models.CharField(max_length=50, verbose_name='职位类型')),
                ('position_name', models.CharField(max_length=20, verbose_name='职位名字')),
                ('start_date', models.DateTimeField(verbose_name='起始时间')),
                ('end_date', models.DateTimeField(verbose_name='终止时间')),
                ('skill', models.CharField(max_length=20, verbose_name='技能')),
                ('description', models.CharField(max_length=500, verbose_name='工作描述')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserInfo'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.WorkExp'),
        ),
    ]
