# Generated by Django 2.1.2 on 2018-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181115_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioninfo',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='岗位状态'),
        ),
    ]
