# Generated by Django 2.1.2 on 2018-11-13 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181113_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='avatar',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='公司图标'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='city',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='createTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='desc',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='公司描述'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='公司邮箱'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='phase',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='公司所在阶段'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='scale',
            field=models.IntegerField(null=True, verbose_name='公司人数'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='tags',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='公司标签'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='type',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='公司类型'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='url',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='公司网站'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='create_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='linestaion',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='地铁线路'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='org',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='index.OrgInfo'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='positionAdvantage',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='职位诱惑'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='subwayline',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='地铁线'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='tags',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='职位标签'),
        ),
    ]
