# Generated by Django 2.1.2 on 2018-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_positioninfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='educationexp',
            name='education',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='学历'),
        ),
    ]
