# Generated by Django 2.1.2 on 2018-11-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20181116_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionresumestatus',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name='面试地址'),
        ),
        migrations.AddField(
            model_name='positionresumestatus',
            name='datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='面试时间'),
        ),
    ]
