# Generated by Django 2.1.2 on 2018-11-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181116_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='lincese',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='营业执照'),
        ),
    ]
