# Generated by Django 2.1.2 on 2018-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181109_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='avatar',
            field=models.CharField(default='', max_length=50, verbose_name='公司图标'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='desc',
            field=models.CharField(default='', max_length=500, verbose_name='公司描述'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='公司邮箱'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='公司名称'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='scale',
            field=models.IntegerField(default=0, verbose_name='公司人数'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='type',
            field=models.CharField(default='', max_length=20, verbose_name='公司类型'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='url',
            field=models.CharField(default='', max_length=20, verbose_name='公司网站'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='工作地址'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='工作城市'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='department',
            field=models.CharField(default='', max_length=20, verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='desc',
            field=models.CharField(default='', max_length=400, verbose_name='职位描述'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='edu_exp',
            field=models.CharField(default='', max_length=20, verbose_name='学历要求'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='end_salary',
            field=models.CharField(default='', max_length=20, verbose_name='最高薪资'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='job_catagory',
            field=models.CharField(default='', max_length=20, verbose_name='工作性质'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='职位名称'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='start_salary',
            field=models.CharField(default='', max_length=20, verbose_name='起始薪资'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='type',
            field=models.CharField(default='', max_length=20, verbose_name='岗位类型'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='work_exp',
            field=models.CharField(default='', max_length=20, verbose_name='工作经验'),
        ),
    ]
