# Generated by Django 2.1.2 on 2018-11-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_orginfo_lincese'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginfo',
            name='authed',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='已经认证'),
        ),
    ]
