# Generated by Django 2.1.2 on 2018-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_positioninfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='工作地址'),
        ),
    ]
