# Generated by Django 2.1.2 on 2018-11-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20181109_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='city',
            field=models.CharField(max_length=20, verbose_name='工作城市'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='department',
            field=models.CharField(max_length=20, verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='desc',
            field=models.CharField(max_length=400, verbose_name='职位描述'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='edu_exp',
            field=models.CharField(max_length=20, verbose_name='学历要求'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='end_salary',
            field=models.CharField(max_length=20, verbose_name='最高薪资'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='job_catagory',
            field=models.CharField(max_length=20, verbose_name='工作性质'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='职位名称'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='start_salary',
            field=models.CharField(max_length=20, verbose_name='起始薪资'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='type',
            field=models.CharField(max_length=20, verbose_name='岗位类型'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='work_exp',
            field=models.CharField(max_length=20, verbose_name='工作经验'),
        ),
    ]
