# Generated by Django 2.1.2 on 2018-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20181109_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='avatar',
            field=models.CharField(max_length=50, verbose_name='公司图标'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='desc',
            field=models.CharField(max_length=500, verbose_name='公司描述'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='公司邮箱'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='scale',
            field=models.IntegerField(verbose_name='公司人数'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='type',
            field=models.CharField(max_length=20, verbose_name='公司类型'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='url',
            field=models.CharField(max_length=20, verbose_name='公司网站'),
        ),
    ]
