# Generated by Django 2.1.2 on 2018-11-10 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20181109_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Label1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='一级标签')),
                ('name', models.CharField(max_length=20, verbose_name='一级标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Label2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='二级标签')),
                ('name', models.CharField(max_length=20, verbose_name='二级标签名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job_Label1', verbose_name='父标签ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Label3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='三级标签')),
                ('name', models.CharField(max_length=20, verbose_name='三级标签名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Job_Label2', verbose_name='父标签ID')),
            ],
        ),
        migrations.AddField(
            model_name='orginfo',
            name='city',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='phase',
            field=models.CharField(default='', max_length=50, verbose_name='公司所在阶段'),
        ),
        migrations.AddField(
            model_name='orginfo',
            name='tags',
            field=models.CharField(default='', max_length=200, verbose_name='公司标签'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='seduction',
            field=models.CharField(default='', max_length=200, verbose_name='职位诱惑'),
        ),
    ]
