# Generated by Django 2.1.2 on 2018-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20181110_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginfo',
            name='city',
            field=models.CharField(max_length=20, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='phase',
            field=models.CharField(max_length=50, verbose_name='公司所在阶段'),
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='tags',
            field=models.CharField(max_length=200, verbose_name='公司标签'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='seduction',
            field=models.CharField(max_length=200, verbose_name='职位诱惑'),
        ),
    ]
