# Generated by Django 2.1.2 on 2018-11-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
