# Generated by Django 2.1.2 on 2018-11-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positioninfo',
            name='seduction',
        ),
        migrations.AddField(
            model_name='orginfo',
            name='createTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='positionAdvantage',
            field=models.CharField(default=None, max_length=200, verbose_name='职位诱惑'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='subwayline',
            field=models.CharField(default=None, max_length=20, verbose_name='地铁线'),
        ),
    ]
