# Generated by Django 2.1.2 on 2018-11-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20181111_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioninfo',
            name='linestaion',
            field=models.CharField(default=None, max_length=200, verbose_name='地铁线路'),
        ),
    ]
