# Generated by Django 2.1.2 on 2018-11-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_positioninfo_linestaion'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioninfo',
            name='distinct',
            field=models.CharField(default=None, max_length=20, verbose_name='区/县'),
        ),
        migrations.AddField(
            model_name='positioninfo',
            name='tags',
            field=models.CharField(default=None, max_length=200, verbose_name='职位标签'),
        ),
    ]
