# Generated by Django 2.1.2 on 2018-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='code_password',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='验证码密码'),
        ),
    ]
