# Generated by Django 2.1.2 on 2018-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='角色'),
        ),
    ]
