# Generated by Django 2.1.2 on 2018-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_code_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='code_password',
        ),
        migrations.AddField(
            model_name='myuser',
            name='complete',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='完善信息'),
        ),
    ]
